---
# tasks file for jenkins-install

- name: Get Jenkins crumb
  uri:
    user: "{{ jenkins_admin_user }}"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
    url: "http://127.0.0.1:8080/crumbIssuer/api/json"
    return_content: yes
    status_code: 200, 404
  register: jenkins_crumb

- name: Set crumb token
  set_fact:
    jenkins_crumb_token: "{{ jenkins_crumb.json.crumbRequestField }}={{ jenkins_crumb.json.crumb }}"

- name: Create job test
  jenkins_job:
    config: "{{ lookup('template', 'templates/test.xml.j2') }}"
    name: test
    url: http://localhost:8080
    user: "{{ jenkins_admin_user }}"
    password: "{{ jenkins_admin_password }}"

- name: Create job package
  jenkins_job:
    config: "{{ lookup('template', 'templates/package.xml.j2') }}"
    name: package
    url: http://localhost:8080
    user: "{{ jenkins_admin_user }}"
    password: "{{ jenkins_admin_password }}"
