---
# tasks file for jenkins-install
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yaml"

- name: Install package
  package:
    name: "{{ item }}"
    state: present
  become: yes
  with_items: "{{ package_required }}"

- name: Include install
  include_tasks: install.yml
  when: jenkins is defined 

- name: Include install
  include_tasks: create_pipeline.yml
